title: Settings
icon: mdi:cog
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: button
            name: Automatic Lights
            entity: input_boolean.light_automations
            icon: mdi:lightbulb-on
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: light_automations

          - type: button
            name: Do Not Disturb
            entity: input_boolean.do_not_disturb
            icon: mdi:minus-circle
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: do_not_disturb

      - type: horizontal-stack
        cards:
          - type: button
            name: Home Sounds
            entity: input_boolean.voice_notifications
            icon: mdi:volume-high
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: voice_notifications

          - type: button
            name: Location Alerts
            entity: input_boolean.zone_alerts
            icon: mdi:map-marker
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: zone_alerts

      - type: horizontal-stack
        cards:
          - type: button
            name: Family Movie
            entity: input_boolean.movie_time
            icon: mdi:filmstrip
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: movie_time

          - type: button
            name: Hourly Report
            entity: input_boolean.hourly_report
            icon: mdi:timer-sand
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: hourly_report

      - type: horizontal-stack
        cards:
          - type: button
            name: Nightly Report
            entity: input_boolean.nightly_report
            icon: mdi:weather-night
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: nightly_report

          - type: button
            name: Go Outside 
            entity: input_boolean.enjoyable_weather_reminders
            icon: mdi:weather-windy-variant
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: enjoyable_weather_reminders

      - type: horizontal-stack
        cards:
          - type: button
            name: Working in Office
            entity: input_boolean.working_in_office_room
            icon: mdi:office-building
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: working_in_office_room

          - type: button
            name: Working in Garage
            entity: input_boolean.working_in_garage
            icon: mdi:garage-alert
            color_type: card
            show_state: "on"
            size: 10%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: working_in_garage

      - type: horizontal-stack
        cards:
          - type: button
            name: Stream Cameras To Chromecast
            entity: input_boolean.stream_camera2chromecast
            icon: mdi:cctv
            color_type: card
            show_state: "on"
            size: 5%
            style:
              - font-weight: bold
              - color: rgb(0, 0, 5)
            state:
              - value: "on"
                color: var(--primary-color)
            action: toggle
            toggle:
              domain: input_boolean
              action: stream_camera2chromecast

  - type: entities
    title: Control Panel
    show_header_toggle: false
    entities:
      - input_number.calendar_remind_before_days
      - input_number.battery_alert_threshold

  - type: entities
    title: Garage Timers
    show_header_toggle: false
    entities:      
      - input_number.garage_lights
      - input_number.garage_shop_lights

  - type: entities
    title: Master Suite Timers
    show_header_toggle: false
    entities:
      - input_number.master_bathroom_lights
      - input_number.master_bathroom_toilet_lights
      - input_number.master_bathroom_shower_exhaust_timer_duration
      - input_number.master_bathroom_toilet_exhaust_timer_duration

  - type: entities
    title: Kids Bathroom Timers
    show_header_toggle: false
    entities:
      - input_number.guest_bathroom_lights
      - input_number.guest_bathroom_exhaust_timer_duration

  - type: entities
    title: Kids Bedroom Closet Timers
    show_header_toggle: false
    entities:
      - input_number.srinika_bedroom_closet_lights
      - input_number.hasika_bedroom_closet_lights

  - type: entities
    title: Alerts & Notifications
    show_header_toggle: false
    entities:
      - input_boolean.garage_door_notifications
      - input_boolean.battery_notifications
      - input_boolean.text_alerts
      - input_boolean.led_alerts
      - input_boolean.security_system_alerts
      - input_boolean.notify_camera_alerts
      - input_boolean.trash_reminders
      - automation.family_room_motion_timer
      - automation.family_room_timer_elapsed

  - type: entities
    title: Bed & Wakeup Times
    show_header_toggle: false
    entities:
      - input_datetime.autumn_bed_time
      - input_datetime.autumn_wakeup_time
      - input_datetime.spring_bed_time
      - input_datetime.spring_wakeup_time
      - input_datetime.summer_bed_time
      - input_datetime.summer_wakeup_time
      - input_datetime.winter_bed_time
      - input_datetime.winter_wakeup_time
