title: Kalavala's Home

views:
  - !include lovelace/00_myhome_view.yaml
  - !include lovelace/01_lights_view.yaml
  - !include lovelace/02_climate_view.yaml
  - !include lovelace/03_camera_view.yaml
  - !include lovelace/04_trash_view.yaml
  - !include lovelace/05_tensorflow_view.yaml
  - !include lovelace/07_system_view.yaml
  - !include lovelace/08_multimedia_view.yaml
  - !include lovelace/09_settings_view.yaml
  - !include lovelace/11_scripts_view.yaml
  - !include lovelace/12_automations_view.yaml
  - !include lovelace/13_qnap_view.yaml