###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Home Assistant
#   @description    :   Bunch of Sensors that are system or environment related
###############################################################################
homeassistant:

sensor:
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: "{{ value }}"
    scan_interval: 86400

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: ens160
      - type: last_boot
