##############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Lights
#   @description    :   Lights, Lights, Lights! All the Lights are here!
###############################################################################
homeassistant:
  customize:
    switch.frontyard_light:
      icon: mdi:lightbulb
      friendly_name: Front Porch Lights
      emulated_hue_name: Front Yard Lights
      homebridge_name: Front Yard Lights

    switch.wemoswitch1:
      icon: mdi:lamp
      friendly_name: Wemo Outlet
      emulated_hue_name: Wemo Outlet
      homebridge_name: Wemo Outlet

    switch.backyard_light:
      icon: mdi:lightbulb
      friendly_name: Backyard Lights
      emulated_hue_name: Backyard Lights
      homebridge_name: Backyard Lights

    switch.front_room:
      friendly_name: Front Room Light
      assumed_state: false
      icon: mdi:lightbulb
    switch.basement_left:
      friendly_name: Basement Theater Lights
      assumed_state: false
      icon: mdi:lightbulb
    switch.basement_right:
      friendly_name: Basement Right Side Lights
      assumed_state: false
      icon: mdi:lightbulb
    switch.kitchen_switch:
      friendly_name: Kitchen Light
      assumed_state: false
      icon: mdi:lightbulb
    switch.office_room:
      friendly_name: Office Room Lights
      assumed_state: false
      icon: mdi:lightbulb
    switch.garage:
      friendly_name: Garage Lights
      icon: mdi:lightbulb

    light.hue_color_lamp_1:
      friendly_name: Family Room Light 1
      color_set: false
    light.hue_color_lamp_2:
      friendly_name: Family Room Light 2
      color_set: false
    light.hue_color_lamp_3:
      friendly_name: Family Room Light 3
      color_set: false
    input_boolean.short_flash:
      icon: mdi:flash
      friendly_name: Short Flash
    input_boolean.long_flash:
      icon: mdi:flash
      friendly_name: Long Flash
    input_boolean.animate_upstairs_lights:
      icon: mdi:flash-outline
      friendly_name: Animate Master Bedroom Lights

input_boolean:
  animate_upstairs_lights:
    name: Animate Master Bedroom Lights
    initial: off
  long_flash:
    name: Long Flash Lights
    initial: off
  short_flash:
    name: Long Flash Lights
    initial: off

light:
  - platform: group
    name: Family Room Lights
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3

  - platform: group
    name: Master Bedroom Lights
    entities:
      - light.master_bedroom_1
      - light.master_bedroom_2

switch:
  - platform: rest
    resource: "http://localhost:8126/container/mqtt/"
    name: MQTT
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
    verify_ssl: true

  - platform: rest
    resource: "http://localhost:8126/container/home-assistant/"
    name: Home Assistant
    body_on: '{"state": "unpause"}'
    body_off: '{"state": "pause"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
    verify_ssl: true

  - platform: rest
    resource: "http://localhost:8126/container/camera_streamer/"
    name: Camera Streamer
    body_on: '{"state": "unpause"}'
    body_off: '{"state": "pause"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
    verify_ssl: true
